# Generated by Django 5.2.6 on 2025-09-08 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_cliente', models.CharField(max_length=100, unique=True)),
                ('dni', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_final', models.DateField(blank=True, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('ficha_ruc', models.CharField(blank=True, max_length=20, null=True)),
                ('codigo_referido', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_referido', models.CharField(blank=True, max_length=100, null=True)),
                ('cuenta_banco_referido', models.CharField(blank=True, max_length=50, null=True)),
                ('cuenta_interbancario_referido', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TarifaOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_tarifa', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('costo_por_porcentaje', models.DecimalField(decimal_places=4, max_digits=18)),
                ('costo_fijo', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name='BCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_bcp', models.CharField(max_length=100, unique=True)),
                ('fecha', models.DateField()),
                ('fecha_valuta', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('sucursal_agencia', models.CharField(blank=True, max_length=100, null=True)),
                ('n_operacion', models.CharField(blank=True, max_length=50, null=True)),
                ('usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('comision', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('lm_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('codigo', models.CharField(blank=True, max_length=4, null=True)),
                ('ganancia_referido', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('cliente', models.ForeignKey(db_column='COD_CLIENTE', on_delete=django.db.models.deletion.CASCADE, to='banco.cliente', to_field='cod_cliente')),
                ('tarifa', models.ForeignKey(db_column='COD_TARIFA', on_delete=django.db.models.deletion.CASCADE, to='banco.tarifaoperacion', to_field='cod_tarifa')),
            ],
        ),
    ]
