# Generated by Django 5.2.6 on 2025-09-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bcp',
            name='saldo_inicial',
        ),
        migrations.AlterField(
            model_name='bcp',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='bcp',
            table='BCP',
        ),
    ]
