# Generated by Django 5.2.6 on 2025-09-15 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0002_remove_bcp_saldo_inicial_alter_bcp_fecha_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tarifaoperacion',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='bcp',
            name='tarifa',
            field=models.ForeignKey(db_column='COD_TARIFA', on_delete=django.db.models.deletion.CASCADE, to='banco.tarifaoperacion'),
        ),
        migrations.AlterModelTable(
            name='bcp',
            table=None,
        ),
    ]
