# Generated by Django 5.2.6 on 2025-09-15 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0003_alter_cliente_options_alter_tarifaoperacion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='CLIENTE',
        ),
        migrations.AlterModelTable(
            name='tarifaoperacion',
            table='TARIFA_OPERACION',
        ),
    ]
