# Generated by Django 5.2.6 on 2025-09-15 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0004_alter_cliente_table_alter_tarifaoperacion_table'),
    ]

    operations = [
    ]
