# Generated by Django 5.2.6 on 2025-09-15 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0005_auto_20250915_1050'),
    ]

    operations = [
    ]
