# Generated by Django 5.2.6 on 2025-09-15 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0006_auto_20250915_1052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bcp',
            options={'managed': False},
        ),
    ]
