# Generated by Django 5.2.6 on 2025-09-15 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0007_alter_bcp_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bcp',
            options={'managed': True},
        ),
    ]
