# Generated by Django 5.2.6 on 2025-09-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0008_alter_bcp_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bcp',
            name='cod_bcp',
            field=models.CharField(blank=True, db_column='COD_BCP', max_length=100, null=True, unique=True),
        ),
        migrations.AlterModelTable(
            name='bcp',
            table='BCP',
        ),
    ]
